version: '3'
services:
  php:
    build: .
    depends_on:
      - mysql
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
  mysql:
    image: mysql:5.7.18
    restart: always
    ports:
      - 3307:3306
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal8

volumes:
  mysql-volume:
